PublicHealthcareSystemApp/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PublicHealthcareSystemApp.Controllers
{
    public class DoctorController : Controller
    {
        // GET: Doctor
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Orders()
        {
            return View();
        }

        public ActionResult Pacients()
        {
            return View();
        }
    }
}

PublicHealthcareSystemApp/Controllers/PharmacyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PublicHealthcareSystemApp.Controllers
{
    public class PharmacyController : Controller
    {
        // GET: Pharmacy
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Orders()
        {
            return View();
        }

        public ActionResult Stock()
        {
            return View();
        }
    }
}

PublicHealthcareSystemApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
	<link href="~/Content/ui-grid.css" rel="stylesheet" />
	<link href="~/Content/gridStyle.css" rel="stylesheet" />
	<link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body ng-app="PublicHCsystemApp">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Med Prio", "UserDetails", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@if (Context.User.Identity.IsAuthenticated && Context.User.IsInRole("User")) {@Html.ActionLink("Acasa", "UserDetails", "Home")}</li>
                    <li>@if (Context.User.Identity.IsAuthenticated && Context.User.IsInRole("User")) {@Html.ActionLink("Istoric medical", "MedicalHistory", "Home")}</li>
                    <li>@if (Context.User.Identity.IsAuthenticated && Context.User.IsInRole("User")) {@Html.ActionLink("Comanda online", "Contact", "Home")}</li>

					<li>@if (Context.User.Identity.IsAuthenticated && Context.User.IsInRole("Pharmacist")){@Html.ActionLink("Comenzi", "Orders", "Pharmacy")}</li>
					<li>@if (Context.User.Identity.IsAuthenticated && Context.User.IsInRole("Pharmacist")){@Html.ActionLink("Stoc", "Stock", "Pharmacy")}</li>

					<li>@if (Context.User.Identity.IsAuthenticated && Context.User.IsInRole("Pharmacist")){@Html.ActionLink("Pacienti", "Pacients", "Doctor")}</li>
					<li>@if (Context.User.Identity.IsAuthenticated && Context.User.IsInRole("Pharmacist")){@Html.ActionLink("Comanda", "Orders", "Doctor")}</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Med Prio</p>
        </footer>
    </div>
	<script src="~/Scripts/angular.min.js"></script>
	<script src="~/Scripts/ui-grid.min.js"></script>
	@Scripts.Render("~/bundles/PublicHCsystemApp")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>